export {default as GithubIcon} from "./GithubIcon"
export {default as InstagramIcon} from "./InstagramIcon"
export {default as AmirankalaIcon} from "./AmirankalaIcon"
export {default as TelegramIcon} from "./TelegramIcon"
export {default as EmailIcon} from "./EmailIcon"
export {default as LinkIcon} from "./LinkIcon"